name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
  env:
    MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
    MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

  steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests -p "test*.py"